name: Gradle Build

on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4

      - name: Set Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Delete the sources and all jar files
        run: rm ./build/libs/*{-sources,-all}.jar

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3arthh4ck-fabric
          path: ./build/libs/*.jar
